# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtX79laoEUkzv35fThpsgfGgkmy8Np4g
"""

import tkinter as tk

def fahrenheit_to_celsius():
    try:
        fahrenheit = float(ent_temperature.get())
        celsius = (fahrenheit - 32) * 5/9
        result_label.config(text=f"Converted: {round(celsius, 2)}\N{DEGREE CELSIUS}")
    except ValueError:
        result_label.config(text="Invalid input")

window = tk.Tk()
window.title("Temperature Converter")
window.resizable(width=False, height=False)

frm_entry = tk.Frame(master=window)
ent_temperature = tk.Entry(master=frm_entry, width=10)
IbI_temp = tk.Label(master=frm_entry, text="\N{DEGREE FAHRENHEIT}")
ent_temperature.grid(row=0, column=0, sticky="e")
IbI_temp.grid(row=0, column=1, sticky="w")

b_convert = tk.Button(master=window, text="\N{RIGHTWARDS BLACK ARROW}", command=fahrenheit_to_celsius)
frm_entry.grid(row=0, column=0, padx=10)
b_convert.grid(row=0, column=1, pady=10)

result_label = tk.Label(master=window, text="")
result_label.grid(row=1, column=0, columnspan=2)

window.mainloop()