# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8gko98fUB-JWjGncdeb_jeoEiAC5upz
"""

import pandas as pd
import numpy as np

# Create the DataFrame
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)

# 1. Print the first three rows
print(df.head(3))

# 2. Delete rows with NaN values
df.dropna(inplace=True)

# 3. Extract 'name' and 'score' columns
name_score_df = df[['name', 'score']]

# 4. Append a new row 'K' to the DataFrame
new_row = pd.Series({'name': 'Suresh', 'score': 15.5, 'attempts': 1, 'qualify': 'yes'}, name='k')
df = df.append(new_row)

# 5. Delete the 'attempts' column
df.drop('attempts', axis=1, inplace=True)

# 6. Add a new column 'Success' based on score
df['Success'] = df['score'].apply(lambda x: 1 if x > 10 else 0)

# 7. Export the DataFrame to a CSV file named 'my_data.csv'
df.to_csv('my_data.csv', sep=';', index=False)