# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MakJJUJGJVcsZ_RbMnB-ZfmRA7NLYz4h
"""

import numpy as np

num_students = int(input("Enter the number of students: "))
num_subjects = int(input("Enter the number of subjects: "))

marks_array = np.empty((num_students, num_subjects))

# Input marks for each student
for i in range(num_students):
    print(f"\nEnter marks for student {i + 1}:")
    for j in range(num_subjects):
        marks_array[i][j] = float(input(f"Subject {j + 1}: "))

# Calculate total marks, percentage, and grade for each student
total_marks = np.sum(marks_array, axis=1)
percentage = (total_marks / (num_subjects * 100)) * 100
grades = np.where(percentage >= 90, 'A+',
np.where(percentage >= 80, 'A',
np.where(percentage >= 70, 'B+',
np.where(percentage >= 60, 'B',
np.where(percentage >= 50, 'C', 'F')))))

# Display the result in tabular format
print("\nStudent\tTotal Marks\tPercentage\tGrade")
for i in range(num_students):
    print(f"{i + 1}\t\t{total_marks[i]}\t\t{percentage[i]:.2f}%\t\t{grades[i]}")